export { ActivitiesCards } from "./Activities";
export { ActivitiesBanner } from "./Activities/index";
export { default as AdminStreaming } from "./AdminStreaming";
export { AreasBanner } from "./Proyects/index";
export { HomeBanner } from "./Home/index";
export { HomeNews } from "./Home/index";
export { HomeLeader } from "./Home/index";
export { ProyectBanner } from "./Proyects/index";
export { default as StreamingBanner } from "./Streaming/StreamingBanner";
export { default as StreamingShows } from "./Streaming/StreamingShows";
export { default as AdminProyectAreas } from "./AdminProyects/AdminProyectAreas";
export { default as Contact } from "./Contact";
export { default as AdminActivitiesCards } from "./AdminActivities/index";
