export const USER_TICKETS = [
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
  {
    name: "Pepito",
    lastName: "Gomez",
    email: "pepito.gomez@gmail.com",
    showTitle: "Show 1",
    isActive: true,
    startDate: new Date(),
    endDate: new Date("4/25/23"),
    key: "arha32qauh462757ea",
    imageURL: "https://images.alphacoders.com/517/517695.jpg",
  },
];
